// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_ztnb_fisher_info_cpp
arma::mat compute_ztnb_fisher_info_cpp(const arma::vec& beta, double theta, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights);
RcppExport SEXP _fasthurdle_compute_ztnb_fisher_info_cpp(SEXP betaSEXP, SEXP thetaSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ztnb_fisher_info_cpp(beta, theta, X, offsetx, weights));
    return rcpp_result_gen;
END_RCPP
}
// optim_count_poisson_cpp
Rcpp::List optim_count_poisson_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_count_poisson_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_count_poisson_cpp(start, Y, X, offsetx, weights, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_count_negbin_cpp
Rcpp::List optim_count_negbin_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_count_negbin_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_count_negbin_cpp(start, Y, X, offsetx, weights, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_count_geom_cpp
Rcpp::List optim_count_geom_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_count_geom_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_count_geom_cpp(start, Y, X, offsetx, weights, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_zero_poisson_cpp
Rcpp::List optim_zero_poisson_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_zero_poisson_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_zero_poisson_cpp(start, Y, X, offsetx, weights, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_zero_negbin_cpp
Rcpp::List optim_zero_negbin_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_zero_negbin_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_zero_negbin_cpp(start, Y, X, offsetx, weights, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_zero_geom_cpp
Rcpp::List optim_zero_geom_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_zero_geom_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_zero_geom_cpp(start, Y, X, offsetx, weights, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_zero_binom_cpp
Rcpp::List optim_zero_binom_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::vec& weights, const std::string& link, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_zero_binom_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP linkSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_zero_binom_cpp(start, Y, X, offsetx, weights, link, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// optim_joint_cpp
Rcpp::List optim_joint_cpp(const arma::vec& start, const arma::vec& Y, const arma::mat& X, const arma::vec& offsetx, const arma::mat& Z, const arma::vec& offsetz, const arma::vec& weights, const std::string& dist, const std::string& zero_dist, const std::string& link, const std::string& method, bool hessian, int maxit, double reltol);
RcppExport SEXP _fasthurdle_optim_joint_cpp(SEXP startSEXP, SEXP YSEXP, SEXP XSEXP, SEXP offsetxSEXP, SEXP ZSEXP, SEXP offsetzSEXP, SEXP weightsSEXP, SEXP distSEXP, SEXP zero_distSEXP, SEXP linkSEXP, SEXP methodSEXP, SEXP hessianSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetz(offsetzSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type zero_dist(zero_distSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_joint_cpp(start, Y, X, offsetx, Z, offsetz, weights, dist, zero_dist, link, method, hessian, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// score_test_count_cpp
Rcpp::List score_test_count_cpp(const arma::vec& null_par, const arma::vec& Y, const arma::mat& X_null, const arma::mat& X_full, const arma::vec& offsetx, const arma::vec& weights, const std::string& dist, bool use_spa, double spa_cutoff);
RcppExport SEXP _fasthurdle_score_test_count_cpp(SEXP null_parSEXP, SEXP YSEXP, SEXP X_nullSEXP, SEXP X_fullSEXP, SEXP offsetxSEXP, SEXP weightsSEXP, SEXP distSEXP, SEXP use_spaSEXP, SEXP spa_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type null_par(null_parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_null(X_nullSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_full(X_fullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< bool >::type use_spa(use_spaSEXP);
    Rcpp::traits::input_parameter< double >::type spa_cutoff(spa_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_count_cpp(null_par, Y, X_null, X_full, offsetx, weights, dist, use_spa, spa_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// score_test_zero_cpp
Rcpp::List score_test_zero_cpp(const arma::vec& null_par, const arma::vec& Y, const arma::mat& Z_null, const arma::mat& Z_full, const arma::vec& offsetz, const arma::vec& weights, bool use_spa, double spa_cutoff);
RcppExport SEXP _fasthurdle_score_test_zero_cpp(SEXP null_parSEXP, SEXP YSEXP, SEXP Z_nullSEXP, SEXP Z_fullSEXP, SEXP offsetzSEXP, SEXP weightsSEXP, SEXP use_spaSEXP, SEXP spa_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type null_par(null_parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_null(Z_nullSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_full(Z_fullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetz(offsetzSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_spa(use_spaSEXP);
    Rcpp::traits::input_parameter< double >::type spa_cutoff(spa_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_zero_cpp(null_par, Y, Z_null, Z_full, offsetz, weights, use_spa, spa_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// compute_negbin_hurdle_fitted_cpp
Rcpp::List compute_negbin_hurdle_fitted_cpp(const arma::vec& coefc, const arma::vec& coefz, const arma::mat& X, const arma::mat& Z, const arma::vec& offsetx, const arma::vec& offsetz, double theta, const arma::vec& y);
RcppExport SEXP _fasthurdle_compute_negbin_hurdle_fitted_cpp(SEXP coefcSEXP, SEXP coefzSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP offsetxSEXP, SEXP offsetzSEXP, SEXP thetaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type coefc(coefcSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coefz(coefzSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetz(offsetzSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_negbin_hurdle_fitted_cpp(coefc, coefz, X, Z, offsetx, offsetz, theta, y));
    return rcpp_result_gen;
END_RCPP
}
// prepare_score_cache_nb_cpp
Rcpp::List prepare_score_cache_nb_cpp(const arma::vec& null_par, const arma::vec& Y, const arma::mat& X_null, const arma::vec& offsetx, const arma::vec& weights);
RcppExport SEXP _fasthurdle_prepare_score_cache_nb_cpp(SEXP null_parSEXP, SEXP YSEXP, SEXP X_nullSEXP, SEXP offsetxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type null_par(null_parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_null(X_nullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offsetx(offsetxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(prepare_score_cache_nb_cpp(null_par, Y, X_null, offsetx, weights));
    return rcpp_result_gen;
END_RCPP
}
// score_test_count_cached_cpp
Rcpp::List score_test_count_cached_cpp(const arma::vec& x_test, const arma::uvec& Y1, const arma::vec& grad_weights, const arma::vec& v_ee, const arma::vec& v_et, const arma::vec& Y_pos, const arma::mat& I_nn_inv, const arma::mat& I_nn_beta_inv, bool beta_inv_ok, const arma::mat& Xnull_vee_t, const arma::mat& X_null_pos, const arma::vec& off_pos, const arma::vec& w_pos, double theta, const arma::vec& beta_null, const arma::vec& mu_pos, const arma::vec& p0_pos, const arma::vec& log_p1_pos, int kx_null, bool use_spa, double spa_cutoff);
RcppExport SEXP _fasthurdle_score_test_count_cached_cpp(SEXP x_testSEXP, SEXP Y1SEXP, SEXP grad_weightsSEXP, SEXP v_eeSEXP, SEXP v_etSEXP, SEXP Y_posSEXP, SEXP I_nn_invSEXP, SEXP I_nn_beta_invSEXP, SEXP beta_inv_okSEXP, SEXP Xnull_vee_tSEXP, SEXP X_null_posSEXP, SEXP off_posSEXP, SEXP w_posSEXP, SEXP thetaSEXP, SEXP beta_nullSEXP, SEXP mu_posSEXP, SEXP p0_posSEXP, SEXP log_p1_posSEXP, SEXP kx_nullSEXP, SEXP use_spaSEXP, SEXP spa_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x_test(x_testSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type grad_weights(grad_weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type v_ee(v_eeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type v_et(v_etSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_pos(Y_posSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type I_nn_inv(I_nn_invSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type I_nn_beta_inv(I_nn_beta_invSEXP);
    Rcpp::traits::input_parameter< bool >::type beta_inv_ok(beta_inv_okSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnull_vee_t(Xnull_vee_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_null_pos(X_null_posSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type off_pos(off_posSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_pos(w_posSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_null(beta_nullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_pos(mu_posSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p0_pos(p0_posSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type log_p1_pos(log_p1_posSEXP);
    Rcpp::traits::input_parameter< int >::type kx_null(kx_nullSEXP);
    Rcpp::traits::input_parameter< bool >::type use_spa(use_spaSEXP);
    Rcpp::traits::input_parameter< double >::type spa_cutoff(spa_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_count_cached_cpp(x_test, Y1, grad_weights, v_ee, v_et, Y_pos, I_nn_inv, I_nn_beta_inv, beta_inv_ok, Xnull_vee_t, X_null_pos, off_pos, w_pos, theta, beta_null, mu_pos, p0_pos, log_p1_pos, kx_null, use_spa, spa_cutoff));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fasthurdle_compute_ztnb_fisher_info_cpp", (DL_FUNC) &_fasthurdle_compute_ztnb_fisher_info_cpp, 5},
    {"_fasthurdle_optim_count_poisson_cpp", (DL_FUNC) &_fasthurdle_optim_count_poisson_cpp, 9},
    {"_fasthurdle_optim_count_negbin_cpp", (DL_FUNC) &_fasthurdle_optim_count_negbin_cpp, 9},
    {"_fasthurdle_optim_count_geom_cpp", (DL_FUNC) &_fasthurdle_optim_count_geom_cpp, 9},
    {"_fasthurdle_optim_zero_poisson_cpp", (DL_FUNC) &_fasthurdle_optim_zero_poisson_cpp, 9},
    {"_fasthurdle_optim_zero_negbin_cpp", (DL_FUNC) &_fasthurdle_optim_zero_negbin_cpp, 9},
    {"_fasthurdle_optim_zero_geom_cpp", (DL_FUNC) &_fasthurdle_optim_zero_geom_cpp, 9},
    {"_fasthurdle_optim_zero_binom_cpp", (DL_FUNC) &_fasthurdle_optim_zero_binom_cpp, 10},
    {"_fasthurdle_optim_joint_cpp", (DL_FUNC) &_fasthurdle_optim_joint_cpp, 14},
    {"_fasthurdle_score_test_count_cpp", (DL_FUNC) &_fasthurdle_score_test_count_cpp, 9},
    {"_fasthurdle_score_test_zero_cpp", (DL_FUNC) &_fasthurdle_score_test_zero_cpp, 8},
    {"_fasthurdle_compute_negbin_hurdle_fitted_cpp", (DL_FUNC) &_fasthurdle_compute_negbin_hurdle_fitted_cpp, 8},
    {"_fasthurdle_prepare_score_cache_nb_cpp", (DL_FUNC) &_fasthurdle_prepare_score_cache_nb_cpp, 5},
    {"_fasthurdle_score_test_count_cached_cpp", (DL_FUNC) &_fasthurdle_score_test_count_cached_cpp, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_fasthurdle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
