# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_ztnb_fisher_info_cpp <- function(beta, theta, X, offsetx, weights) {
    .Call(`_fasthurdle_compute_ztnb_fisher_info_cpp`, beta, theta, X, offsetx, weights)
}

optim_count_poisson_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_count_poisson_cpp`, start, Y, X, offsetx, weights, method, hessian, maxit, reltol)
}

optim_count_negbin_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_count_negbin_cpp`, start, Y, X, offsetx, weights, method, hessian, maxit, reltol)
}

optim_count_geom_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_count_geom_cpp`, start, Y, X, offsetx, weights, method, hessian, maxit, reltol)
}

optim_zero_poisson_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_zero_poisson_cpp`, start, Y, X, offsetx, weights, method, hessian, maxit, reltol)
}

optim_zero_negbin_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_zero_negbin_cpp`, start, Y, X, offsetx, weights, method, hessian, maxit, reltol)
}

optim_zero_geom_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_zero_geom_cpp`, start, Y, X, offsetx, weights, method, hessian, maxit, reltol)
}

optim_zero_binom_cpp <- function(start, Y, X, offsetx, weights, link = "logit", method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_zero_binom_cpp`, start, Y, X, offsetx, weights, link, method, hessian, maxit, reltol)
}

optim_joint_cpp <- function(start, Y, X, offsetx, Z, offsetz, weights, dist = "poisson", zero_dist = "binomial", link = "logit", method = "BFGS", hessian = TRUE, maxit = 10000L, reltol = -1.0) {
    .Call(`_fasthurdle_optim_joint_cpp`, start, Y, X, offsetx, Z, offsetz, weights, dist, zero_dist, link, method, hessian, maxit, reltol)
}

score_test_count_cpp <- function(null_par, Y, X_null, X_full, offsetx, weights, dist = "negbin", use_spa = FALSE, spa_cutoff = 2.0) {
    .Call(`_fasthurdle_score_test_count_cpp`, null_par, Y, X_null, X_full, offsetx, weights, dist, use_spa, spa_cutoff)
}

compute_negbin_hurdle_fitted_cpp <- function(coefc, coefz, X, Z, offsetx, offsetz, theta, y) {
    .Call(`_fasthurdle_compute_negbin_hurdle_fitted_cpp`, coefc, coefz, X, Z, offsetx, offsetz, theta, y)
}

