# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optim_count_poisson_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_count_poisson_cpp`, start, Y, X, offsetx, weights, method, hessian)
}

optim_count_negbin_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_count_negbin_cpp`, start, Y, X, offsetx, weights, method, hessian)
}

optim_count_geom_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_count_geom_cpp`, start, Y, X, offsetx, weights, method, hessian)
}

optim_zero_poisson_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_zero_poisson_cpp`, start, Y, X, offsetx, weights, method, hessian)
}

optim_zero_negbin_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_zero_negbin_cpp`, start, Y, X, offsetx, weights, method, hessian)
}

optim_zero_geom_cpp <- function(start, Y, X, offsetx, weights, method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_zero_geom_cpp`, start, Y, X, offsetx, weights, method, hessian)
}

optim_zero_binom_cpp <- function(start, Y, X, offsetx, weights, link = "logit", method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_zero_binom_cpp`, start, Y, X, offsetx, weights, link, method, hessian)
}

optim_joint_cpp <- function(start, Y, X, offsetx, Z, offsetz, weights, dist = "poisson", zero_dist = "binomial", link = "logit", method = "BFGS", hessian = TRUE) {
    .Call(`_fasthurdle_optim_joint_cpp`, start, Y, X, offsetx, Z, offsetz, weights, dist, zero_dist, link, method, hessian)
}

